version: '3'

services:
  app:
    # depends_on:
    #   - db
    container_name: nest-app
    image: lagunasdaniel001/teslo-shop:1.1.0
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_VERSION: ${APP_VERSION}
      STAGE: ${STAGE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      PORT: ${PORT}
      HOST_API: ${HOST_API}
      JWT_SECRET: ${JWT_SECRET}
    restart: always

  # db:
  #   container_name: ${DB_NAME}
  #   image: postgres:14.3
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #   volumes:
  #     - postgres-db:/var/lib/postgresql/data
  #   restart: always
    
# volumes:
#   postgres-db:
#     external: false
  