version: '3'


services:
  app:
    container_name: nest-app
    build: 
      context: .              # Esto le dice que busque al archivo Dockerfile en este directorio
      target: ${STAGE}            # Le dice que multi-state build se creara para desarrollo
      dockerfile: Dockerfile  # Se especifica lo que es el dockerfile aunque no es necesario
      
    image: lagunasdaniel001/teslo-shop-backend
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_VERSION: ${APP_VERSION}
      STAGE: ${STAGE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      PORT: ${PORT}
      HOST_API: ${HOST_API}
      JWT_SECRET: ${JWT_SECRET}
    
  db:
    container_name: ${DB_NAME}
    image: postgres:14.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: always


volumes:
  postgres-db:
    external: false